In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

1.12.1+cu116


In [3]:
scalar =  torch.tensor(5)
scalar

tensor(5)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
scalar.item()

5

In [7]:
vector = torch.tensor([1, 2, 3, 4, 5])
print(vector)

tensor([1, 2, 3, 4, 5])


In [8]:
MATRIX = torch.tensor([[1, 2, 3], 
                       [4, 5, 6]])
MATRIX.shape

torch.Size([2, 3])

In [9]:
TENSOR = torch.tensor([[[1, 2, 3], 
                        [4, 5, 6]], 
                       [[7, 8, 9], 
                        [10, 11, 12]]])
TENSOR.shape

torch.Size([2, 2, 3])

In [10]:
torch.random.manual_seed(42)
torch.randn(3, 3)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [11]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.arange(0, 10, step=0.2)

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000, 3.0000, 3.2000, 3.4000,
        3.6000, 3.8000, 4.0000, 4.2000, 4.4000, 4.6000, 4.8000, 5.0000, 5.2000,
        5.4000, 5.6000, 5.8000, 6.0000, 6.2000, 6.4000, 6.6000, 6.8000, 7.0000,
        7.2000, 7.4000, 7.6000, 7.8000, 8.0000, 8.2000, 8.4000, 8.6000, 8.8000,
        9.0000, 9.2000, 9.4000, 9.6000, 9.8000])

In [13]:
torch.zeros_like(MATRIX)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.randn_like(MATRIX, dtype=torch.float)

tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890]])

In [15]:
net1 = torch.tensor([1, 2, 3, 4, 5], 
                    dtype=torch.float, 
                    device='cuda', requires_grad=True)

In [16]:
net_16 = torch.tensor([1, 2, 3, 4, 5], 
                      dtype=torch.float16, 
                      device='cuda', 
                      requires_grad=True)

In [17]:
net32 = torch.tensor([1, 2, 3, 4, 5], 
                    dtype=torch.float, 
                    device='cuda', requires_grad=True)

In [18]:
net1.detach()

tensor([1., 2., 3., 4., 5.], device='cuda:0')

In [19]:
net_32 = net_16.type(torch.float32)
print(net_32.dtype)
print(net_32.detach().cpu().numpy())

torch.float32
[1. 2. 3. 4. 5.]


In [20]:
torch.mul(net1, net_32)

tensor([ 1.,  4.,  9., 16., 25.], device='cuda:0', grad_fn=<MulBackward0>)

In [21]:
torch.add(net1, net_32)

tensor([ 2.,  4.,  6.,  8., 10.], device='cuda:0', grad_fn=<AddBackward0>)

In [22]:
matrix_shape = torch.Size([10, 1500, 40])

In [23]:
A = torch.rand(matrix_shape)
B = torch.rand(matrix_shape)
# print(B[0])

In [24]:
%%time
for i in range(10):
    C = torch.matmul(A.to('cuda'), B.mT.to('cuda'))

CPU times: user 295 ms, sys: 99.5 ms, total: 394 ms
Wall time: 396 ms


In [25]:
%%time
for i in range(10):
    A @ B.mT

CPU times: user 1.08 s, sys: 290 ms, total: 1.37 s
Wall time: 218 ms


In [26]:
argmin = torch.argmin(net1.detach().cpu())
argmax = torch.argmax(net1.detach().cpu())
print(argmin, argmax)

tensor(0) tensor(4)


In [27]:
net1[argmax]

tensor(5., device='cuda:0', grad_fn=<SelectBackward0>)

In [28]:
net1.reshape(5, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]], device='cuda:0', grad_fn=<ReshapeAliasBackward0>)

In [29]:
torch.cat([net1, net1])

tensor([1., 2., 3., 4., 5., 1., 2., 3., 4., 5.], device='cuda:0',
       grad_fn=<CatBackward0>)

In [30]:
torch.stack([net1, net1])

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]], device='cuda:0', grad_fn=<StackBackward0>)

In [31]:
x = torch.rand([3, 18])
x

tensor([[0.2529, 0.9982, 0.3181, 0.0633, 0.3445, 0.9914, 0.2857, 0.1437, 0.0347,
         0.5107, 0.9995, 0.3696, 0.3876, 0.7393, 0.0432, 0.7261, 0.0564, 0.3705],
        [0.6347, 0.1379, 0.0422, 0.0811, 0.8747, 0.4618, 0.7892, 0.6784, 0.8498,
         0.8628, 0.8723, 0.1681, 0.7518, 0.5260, 0.1878, 0.4432, 0.3610, 0.2314],
        [0.3064, 0.9535, 0.7075, 0.0422, 0.4874, 0.9819, 0.9659, 0.8048, 0.5549,
         0.7110, 0.2435, 0.1595, 0.5959, 0.6584, 0.2816, 0.1363, 0.7147, 0.6863]])

In [32]:
xr = x.reshape([3, 3, 6])
xr, xr.shape

(tensor([[[0.2529, 0.9982, 0.3181, 0.0633, 0.3445, 0.9914],
          [0.2857, 0.1437, 0.0347, 0.5107, 0.9995, 0.3696],
          [0.3876, 0.7393, 0.0432, 0.7261, 0.0564, 0.3705]],
 
         [[0.6347, 0.1379, 0.0422, 0.0811, 0.8747, 0.4618],
          [0.7892, 0.6784, 0.8498, 0.8628, 0.8723, 0.1681],
          [0.7518, 0.5260, 0.1878, 0.4432, 0.3610, 0.2314]],
 
         [[0.3064, 0.9535, 0.7075, 0.0422, 0.4874, 0.9819],
          [0.9659, 0.8048, 0.5549, 0.7110, 0.2435, 0.1595],
          [0.5959, 0.6584, 0.2816, 0.1363, 0.7147, 0.6863]]]),
 torch.Size([3, 3, 6]))

In [33]:
xv = x.view([3, 6, 3])
xv, xv.shape

(tensor([[[0.2529, 0.9982, 0.3181],
          [0.0633, 0.3445, 0.9914],
          [0.2857, 0.1437, 0.0347],
          [0.5107, 0.9995, 0.3696],
          [0.3876, 0.7393, 0.0432],
          [0.7261, 0.0564, 0.3705]],
 
         [[0.6347, 0.1379, 0.0422],
          [0.0811, 0.8747, 0.4618],
          [0.7892, 0.6784, 0.8498],
          [0.8628, 0.8723, 0.1681],
          [0.7518, 0.5260, 0.1878],
          [0.4432, 0.3610, 0.2314]],
 
         [[0.3064, 0.9535, 0.7075],
          [0.0422, 0.4874, 0.9819],
          [0.9659, 0.8048, 0.5549],
          [0.7110, 0.2435, 0.1595],
          [0.5959, 0.6584, 0.2816],
          [0.1363, 0.7147, 0.6863]]]),
 torch.Size([3, 6, 3]))

In [34]:
x.unsqueeze(0)

tensor([[[0.2529, 0.9982, 0.3181, 0.0633, 0.3445, 0.9914, 0.2857, 0.1437,
          0.0347, 0.5107, 0.9995, 0.3696, 0.3876, 0.7393, 0.0432, 0.7261,
          0.0564, 0.3705],
         [0.6347, 0.1379, 0.0422, 0.0811, 0.8747, 0.4618, 0.7892, 0.6784,
          0.8498, 0.8628, 0.8723, 0.1681, 0.7518, 0.5260, 0.1878, 0.4432,
          0.3610, 0.2314],
         [0.3064, 0.9535, 0.7075, 0.0422, 0.4874, 0.9819, 0.9659, 0.8048,
          0.5549, 0.7110, 0.2435, 0.1595, 0.5959, 0.6584, 0.2816, 0.1363,
          0.7147, 0.6863]]])

In [35]:
torch.stack([xv, xv], dim=2)

tensor([[[[0.2529, 0.9982, 0.3181],
          [0.2529, 0.9982, 0.3181]],

         [[0.0633, 0.3445, 0.9914],
          [0.0633, 0.3445, 0.9914]],

         [[0.2857, 0.1437, 0.0347],
          [0.2857, 0.1437, 0.0347]],

         [[0.5107, 0.9995, 0.3696],
          [0.5107, 0.9995, 0.3696]],

         [[0.3876, 0.7393, 0.0432],
          [0.3876, 0.7393, 0.0432]],

         [[0.7261, 0.0564, 0.3705],
          [0.7261, 0.0564, 0.3705]]],


        [[[0.6347, 0.1379, 0.0422],
          [0.6347, 0.1379, 0.0422]],

         [[0.0811, 0.8747, 0.4618],
          [0.0811, 0.8747, 0.4618]],

         [[0.7892, 0.6784, 0.8498],
          [0.7892, 0.6784, 0.8498]],

         [[0.8628, 0.8723, 0.1681],
          [0.8628, 0.8723, 0.1681]],

         [[0.7518, 0.5260, 0.1878],
          [0.7518, 0.5260, 0.1878]],

         [[0.4432, 0.3610, 0.2314],
          [0.4432, 0.3610, 0.2314]]],


        [[[0.3064, 0.9535, 0.7075],
          [0.3064, 0.9535, 0.7075]],

         [[0.0422, 0.4874, 0.9819]

In [36]:
torch.vstack([xv, xv]).shape

torch.Size([6, 6, 3])

In [37]:
torch.hstack([xv, xv]).shape

torch.Size([3, 12, 3])

In [38]:
xv_ = xv.unsqueeze(0)
xv_.shape

torch.Size([1, 3, 6, 3])

In [39]:
seed = torch.seed()
torch.manual_seed(5)
torch.rand(8)

tensor([0.8303, 0.1261, 0.9075, 0.8199, 0.9201, 0.1166, 0.1644, 0.7379])

In [40]:
torch.rand(5)

tensor([0.0333, 0.9942, 0.6064, 0.5646, 0.0724])

In [41]:
import numpy
import random

worker_seed = torch.initial_seed() % 2**32
numpy.random.seed(worker_seed)
random.seed(worker_seed)
gg = torch.Generator()
torch.manual_seed(worker_seed)

In [42]:
torch.rand(5)

tensor([0.8303, 0.1261, 0.9075, 0.8199, 0.9201])

Studying CNN

In [43]:
torch.manual_seed(42)
images = torch.randn(32, 3, 64, 64)
test_feature = images[0]
print(f"Test feature: {test_feature.shape}")

conv_layer = nn.Conv2d(in_channels=3, out_channels=10, kernel_size=2, stride=1, padding=0)
conv_ouput = conv_layer(test_feature)
print(f"Conv output: {conv_ouput.shape}")
# summary(conv_layer, input_size=test_feature.shape, device=DEVICE)

Test feature: torch.Size([3, 64, 64])
Conv output: torch.Size([10, 63, 63])


In [44]:
max_pool = torch.nn.MaxPool2d(kernel_size=2, stride=1)
print(f"Before Max pool: {conv_ouput.shape}")

max_pool_output = max_pool(conv_ouput)
print(f"Max pool output: {max_pool_output.shape}")

Before Max pool: torch.Size([10, 63, 63])
Max pool output: torch.Size([10, 62, 62])
